_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 1
                - 5
                - 35
                - 41
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 35
                - 41
                - 53
                - 55
                - 105
            "3":
                - 1
                - 2
                - 16
                - 23
                - 24
                - 55
            "4": 3.12.0
            "5": 0.19.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
batch_size:
    value: 64
epochs:
    value: 50
learning_rate:
    value: 0.0001
