_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 35
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 41
                - 53
                - 55
            "3":
                - 1
                - 16
                - 23
                - 24
                - 55
            "4": 3.11.9
            "5": 0.19.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
batch_size:
    value: 64
leraning_rate:
    value: 0.0001
num_epochs:
    value: 50
num_workers:
    value: 4
